# Generated by Django 6.0.3 on 2026-05-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryrating',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
