# Generated by Django 6.0.3 on 2026-03-26 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffering',
            name='mentors',
        ),
        migrations.AddField(
            model_name='course',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='mentored_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
