# Generated by Django 6.0.3 on 2026-03-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('courses', '0002_remove_courseoffering_mentors_course_mentors'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course', 'semester')},
        ),
    ]
