# Generated by Django 6.0.3 on 2026-03-31 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courseoffering_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='status',
        ),
    ]
