# Generated by Django 6.0.3 on 2026-04-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
