# Generated by Django 6.0.3 on 2026-05-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorapplication',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='mentor_applications/'),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='file1_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='mentor_applications/'),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='file2_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='review_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
