# Generated by Django 6.0.3 on 2026-05-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_real_session',
            field=models.BooleanField(default=False),
        ),
    ]
