# Generated by Django 6.0.3 on 2026-05-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_mentorapplication_file1_mentorapplication_file1_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorapplication',
            name='file1_type',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='file2_type',
        ),
    ]
