# Generated by Django 6.0.3 on 2026-05-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_remove_mentorapplication_file1_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorapplication',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
