# Generated by Django 6.0.3 on 2026-05-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='supervisor',
        ),
    ]
